# Generated by Django 5.0 on 2023-12-12 06:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                (
                    "base_price",
                    models.DecimalField(
                        choices=[
                            (Decimal("0"), "$0.00"),
                            (Decimal("0.25"), "$0.25"),
                            (Decimal("0.5"), "$0.50"),
                            (Decimal("1"), "$1.00"),
                            (Decimal("1.5"), "$1.50"),
                            (Decimal("2"), "$2.00"),
                            (Decimal("2"), "$2.00"),
                            (Decimal("2.5"), "$2.50"),
                            (Decimal("3"), "$3.00"),
                            (Decimal("3.5"), "$3.50"),
                            (Decimal("4"), "$4.00"),
                            (Decimal("4.5"), "$4.50"),
                            (Decimal("5"), "$5.00"),
                        ],
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                    ),
                ),
                (
                    "additional_price",
                    models.DecimalField(
                        choices=[
                            (Decimal("0"), "$0.00"),
                            (Decimal("0.25"), "$0.25"),
                            (Decimal("0.5"), "$0.50"),
                            (Decimal("1"), "$1.00"),
                            (Decimal("1.5"), "$1.50"),
                            (Decimal("2"), "$2.00"),
                            (Decimal("2"), "$2.00"),
                            (Decimal("2.5"), "$2.50"),
                            (Decimal("3"), "$3.00"),
                            (Decimal("3.5"), "$3.50"),
                            (Decimal("4"), "$4.00"),
                            (Decimal("4.5"), "$4.50"),
                            (Decimal("5"), "$5.00"),
                        ],
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cheese",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                (
                    "base_price",
                    models.DecimalField(
                        choices=[
                            (Decimal("0"), "$0.00"),
                            (Decimal("0.25"), "$0.25"),
                            (Decimal("0.5"), "$0.50"),
                            (Decimal("1"), "$1.00"),
                            (Decimal("1.5"), "$1.50"),
                            (Decimal("2"), "$2.00"),
                            (Decimal("2"), "$2.00"),
                            (Decimal("2.5"), "$2.50"),
                            (Decimal("3"), "$3.00"),
                            (Decimal("3.5"), "$3.50"),
                            (Decimal("4"), "$4.00"),
                            (Decimal("4.5"), "$4.50"),
                            (Decimal("5"), "$5.00"),
                        ],
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                    ),
                ),
                (
                    "additional_price",
                    models.DecimalField(
                        choices=[
                            (Decimal("0"), "$0.00"),
                            (Decimal("0.25"), "$0.25"),
                            (Decimal("0.5"), "$0.50"),
                            (Decimal("1"), "$1.00"),
                            (Decimal("1.5"), "$1.50"),
                            (Decimal("2"), "$2.00"),
                            (Decimal("2"), "$2.00"),
                            (Decimal("2.5"), "$2.50"),
                            (Decimal("3"), "$3.00"),
                            (Decimal("3.5"), "$3.50"),
                            (Decimal("4"), "$4.00"),
                            (Decimal("4.5"), "$4.50"),
                            (Decimal("5"), "$5.00"),
                        ],
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Drink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                (
                    "additional_price",
                    models.DecimalField(
                        choices=[
                            (Decimal("0"), "$0.00"),
                            (Decimal("0.25"), "$0.25"),
                            (Decimal("0.5"), "$0.50"),
                            (Decimal("1"), "$1.00"),
                            (Decimal("1.5"), "$1.50"),
                            (Decimal("2"), "$2.00"),
                            (Decimal("2"), "$2.00"),
                            (Decimal("2.5"), "$2.50"),
                            (Decimal("3"), "$3.00"),
                            (Decimal("3.5"), "$3.50"),
                            (Decimal("4"), "$4.00"),
                            (Decimal("4.5"), "$4.50"),
                            (Decimal("5"), "$5.00"),
                        ],
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "patty_count",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=1,
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "base_price",
                    models.DecimalField(
                        choices=[
                            (Decimal("0"), "$0.00"),
                            (Decimal("0.25"), "$0.25"),
                            (Decimal("0.5"), "$0.50"),
                            (Decimal("1"), "$1.00"),
                            (Decimal("1.5"), "$1.50"),
                            (Decimal("2"), "$2.00"),
                            (Decimal("2"), "$2.00"),
                            (Decimal("2.5"), "$2.50"),
                            (Decimal("3"), "$3.00"),
                            (Decimal("3.5"), "$3.50"),
                            (Decimal("4"), "$4.00"),
                            (Decimal("4.5"), "$4.50"),
                            (Decimal("5"), "$5.00"),
                        ],
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                    ),
                ),
                (
                    "additional_price",
                    models.DecimalField(
                        choices=[
                            (Decimal("0"), "$0.00"),
                            (Decimal("0.25"), "$0.25"),
                            (Decimal("0.5"), "$0.50"),
                            (Decimal("1"), "$1.00"),
                            (Decimal("1.5"), "$1.50"),
                            (Decimal("2"), "$2.00"),
                            (Decimal("2"), "$2.00"),
                            (Decimal("2.5"), "$2.50"),
                            (Decimal("3"), "$3.00"),
                            (Decimal("3.5"), "$3.50"),
                            (Decimal("4"), "$4.00"),
                            (Decimal("4.5"), "$4.50"),
                            (Decimal("5"), "$5.00"),
                        ],
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sauce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                (
                    "base_price",
                    models.DecimalField(
                        choices=[
                            (Decimal("0"), "$0.00"),
                            (Decimal("0.25"), "$0.25"),
                            (Decimal("0.5"), "$0.50"),
                            (Decimal("1"), "$1.00"),
                            (Decimal("1.5"), "$1.50"),
                            (Decimal("2"), "$2.00"),
                            (Decimal("2"), "$2.00"),
                            (Decimal("2.5"), "$2.50"),
                            (Decimal("3"), "$3.00"),
                            (Decimal("3.5"), "$3.50"),
                            (Decimal("4"), "$4.00"),
                            (Decimal("4.5"), "$4.50"),
                            (Decimal("5"), "$5.00"),
                        ],
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                    ),
                ),
                (
                    "additional_price",
                    models.DecimalField(
                        choices=[
                            (Decimal("0"), "$0.00"),
                            (Decimal("0.25"), "$0.25"),
                            (Decimal("0.5"), "$0.50"),
                            (Decimal("1"), "$1.00"),
                            (Decimal("1.5"), "$1.50"),
                            (Decimal("2"), "$2.00"),
                            (Decimal("2"), "$2.00"),
                            (Decimal("2.5"), "$2.50"),
                            (Decimal("3"), "$3.00"),
                            (Decimal("3.5"), "$3.50"),
                            (Decimal("4"), "$4.00"),
                            (Decimal("4.5"), "$4.50"),
                            (Decimal("5"), "$5.00"),
                        ],
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Side",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                (
                    "additional_price",
                    models.DecimalField(
                        choices=[
                            (Decimal("0"), "$0.00"),
                            (Decimal("0.25"), "$0.25"),
                            (Decimal("0.5"), "$0.50"),
                            (Decimal("1"), "$1.00"),
                            (Decimal("1.5"), "$1.50"),
                            (Decimal("2"), "$2.00"),
                            (Decimal("2"), "$2.00"),
                            (Decimal("2.5"), "$2.50"),
                            (Decimal("3"), "$3.00"),
                            (Decimal("3.5"), "$3.50"),
                            (Decimal("4"), "$4.00"),
                            (Decimal("4.5"), "$4.50"),
                            (Decimal("5"), "$5.00"),
                        ],
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Topping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                (
                    "base_price",
                    models.DecimalField(
                        choices=[
                            (Decimal("0"), "$0.00"),
                            (Decimal("0.25"), "$0.25"),
                            (Decimal("0.5"), "$0.50"),
                            (Decimal("1"), "$1.00"),
                            (Decimal("1.5"), "$1.50"),
                            (Decimal("2"), "$2.00"),
                            (Decimal("2"), "$2.00"),
                            (Decimal("2.5"), "$2.50"),
                            (Decimal("3"), "$3.00"),
                            (Decimal("3.5"), "$3.50"),
                            (Decimal("4"), "$4.00"),
                            (Decimal("4.5"), "$4.50"),
                            (Decimal("5"), "$5.00"),
                        ],
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                    ),
                ),
                (
                    "additional_price",
                    models.DecimalField(
                        choices=[
                            (Decimal("0"), "$0.00"),
                            (Decimal("0.25"), "$0.25"),
                            (Decimal("0.5"), "$0.50"),
                            (Decimal("1"), "$1.00"),
                            (Decimal("1.5"), "$1.50"),
                            (Decimal("2"), "$2.00"),
                            (Decimal("2"), "$2.00"),
                            (Decimal("2.5"), "$2.50"),
                            (Decimal("3"), "$3.00"),
                            (Decimal("3.5"), "$3.50"),
                            (Decimal("4"), "$4.00"),
                            (Decimal("4.5"), "$4.50"),
                            (Decimal("5"), "$5.00"),
                        ],
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Burger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "bun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="burgorders.bun"
                    ),
                ),
                (
                    "cheese",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="burgorders.cheese",
                    ),
                ),
                (
                    "patty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="burgorders.patty",
                    ),
                ),
                ("sauces", models.ManyToManyField(to="burgorders.sauce")),
                ("toppings", models.ManyToManyField(to="burgorders.topping")),
            ],
        ),
        migrations.CreateModel(
            name="Combo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "burger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="burgorders.burger",
                    ),
                ),
                (
                    "drink",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="burgorders.drink",
                    ),
                ),
                (
                    "side",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="burgorders.side",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "burgers",
                    models.ManyToManyField(
                        related_name="orders", to="burgorders.burger"
                    ),
                ),
                (
                    "combos",
                    models.ManyToManyField(
                        related_name="orders", to="burgorders.combo"
                    ),
                ),
                (
                    "drinks",
                    models.ManyToManyField(
                        related_name="orders", to="burgorders.drink"
                    ),
                ),
                (
                    "sides",
                    models.ManyToManyField(related_name="orders", to="burgorders.side"),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
    ]
