# Generated by Django 5.0 on 2023-12-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("burgorders", "0002_alter_patty_options_alter_bun_additional_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="burger",
            name="is_signature",
            field=models.BooleanField(default=False),
        ),
    ]
