# Generated by Django 5.0 on 2023-12-13 19:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("burgorders", "0004_rename_is_signature_burger_mysignature"),
    ]

    operations = [
        migrations.RenameField(
            model_name="burger",
            old_name="MySignature",
            new_name="is_signature",
        ),
    ]
